use_frameworks!

target 'MHTableView_Example' do
  pod 'MHTableView', :path => '../'

  target 'MHTableView_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
